name: 🐛 Bug Report
description: Report a bug or unexpected behavior in the Mergington High School system
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! This template will help gather all the information needed for Copilot to understand and fix the issue.

  - type: input
    id: summary
    attributes:
      label: Bug Summary
      description: A clear and concise description of what the bug is
      placeholder: "Example: Students cannot sign up for activities - signup button doesn't work"
    validations:
      required: true

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe what is currently happening
      placeholder: "Example: When I click the 'Sign Up' button for an activity, nothing happens. No error message appears and the student is not added to the activity."
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what should happen instead
      placeholder: "Example: When clicking 'Sign Up', the student should be added to the activity and see a confirmation message."
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the bug
      placeholder: |
        1. Go to the activities page at http://localhost:8000
        2. Click on any activity to view details
        3. Enter a valid email address
        4. Click the 'Sign Up' button
        5. Notice that nothing happens
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Browser, operating system, or other relevant environment details
      placeholder: "Example: Chrome 120, Windows 11, or Firefox 121, macOS"

  - type: textarea
    id: error-messages
    attributes:
      label: Error Messages or Console Output
      description: Include any error messages, console logs, or relevant output
      placeholder: "Paste any error messages from browser console (F12) or server logs here"

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How will we know this bug is fixed?
      placeholder: |
        - [ ] Students can successfully sign up for activities
        - [ ] Confirmation message appears after signup
        - [ ] Student count increases on the activity page
        - [ ] No JavaScript errors in browser console
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context and Hints
      description: Any other information that might be helpful for debugging
      placeholder: |
        - Which specific files might need to be checked (e.g., frontend JavaScript, backend API endpoints)
        - Any recent changes that might have caused this
        - Suspected root cause or debugging hints
        - Related issues or similar problems

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Level
      description: How severe is this bug?
      options:
        - label: Critical - System is completely broken
        - label: High - Major functionality is broken
        - label: Medium - Some functionality is broken but workarounds exist
        - label: Low - Minor issue or cosmetic problem